/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUSINESS.Facade;
import DTO.PersonaDTO;
import java.awt.Color;
import java.sql.Array;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Braro
 */
public class FormAdministrador extends javax.swing.JFrame {

    private Facade faca;
    private FormIniciarSesion sesion;
    private String nomUsuario;
    private String idPersona; 
    private String parte2Id;
    /**
     * Creates new form FormAdministrador
     */
    public FormAdministrador( ArrayList<String> privilegios) {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        faca = new Facade();
       
        //cargar privilegio de la persona
        cargarPrivilegios(privilegios);
        
        //cargar datos a tabla
        mostrarTablaUsuario();
        
        panBitacora.setEnabledAt(1,false);
        panBitacora.setEnabledAt(2,false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panBitacora = new javax.swing.JTabbedPane();
        panVisualizarUsuario = new javax.swing.JPanel();
        btnCrearUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        panCrearUsuario = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombrePersona = new javax.swing.JTextField();
        txtApellidoPersona = new javax.swing.JTextField();
        txtCorreoPersona = new javax.swing.JTextField();
        txtCedulaPersona = new javax.swing.JTextField();
        txtTelefonoPersona = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtUsuarioPersona = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtContraseñaPersona = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCodigoSeguridadPersona = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        panEditarUsuario = new javax.swing.JPanel();
        panDatosUsuario = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtNombreActualizar = new javax.swing.JTextField();
        txtApellidoActualizar = new javax.swing.JTextField();
        txtCorreoActualizar = new javax.swing.JTextField();
        txtCedulaActualizar = new javax.swing.JTextField();
        txtTelefonoActualizar = new javax.swing.JTextField();
        lblNumeroId = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        panDatosInicio = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtUsuarioActualizar = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtContraseñaActualizar = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtCodigoSeguridadActualizar = new javax.swing.JTextField();
        btnregresar = new javax.swing.JButton();
        btnActualizat = new javax.swing.JButton();
        panAñadirRol = new javax.swing.JPanel();
        lblReferencia = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtNuevoRol = new javax.swing.JTextField();
        btnAgregarRol = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstListaPersonas = new javax.swing.JList<>();
        btnAgregarRolPersona = new javax.swing.JButton();
        cmbRol = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panAñadirPrvilegios = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        cmbRequerimientos = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        btnAgregarPrivilegios = new javax.swing.JButton();
        lblMensajePrivilegios = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBitacora = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panBitacora.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 255), null, null));

        panVisualizarUsuario.setBackground(new java.awt.Color(255, 255, 255));
        panVisualizarUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                panVisualizarUsuarioFocusLost(evt);
            }
        });
        panVisualizarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panVisualizarUsuarioMouseClicked(evt);
            }
        });

        btnCrearUsuario.setBackground(new java.awt.Color(51, 102, 255));
        btnCrearUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCrearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/editar.png"))); // NOI18N
        btnCrearUsuario.setText("Crear Nuevo Usuario");
        btnCrearUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.blue, java.awt.Color.white, null, null));
        btnCrearUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearUsuarioMouseExited(evt);
            }
        });
        btnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuarioActionPerformed(evt);
            }
        });

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Nombre", "Email", "Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblDatos.setEditingColumn(0);
        tblDatos.setEditingRow(0);
        tblDatos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblDatos);
        if (tblDatos.getColumnModel().getColumnCount() > 0) {
            tblDatos.getColumnModel().getColumn(0).setPreferredWidth(3);
            tblDatos.getColumnModel().getColumn(2).setPreferredWidth(90);
        }

        jButton2.setBackground(new java.awt.Color(51, 102, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Buscar");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.white, null, null));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnActualizar.setBackground(new java.awt.Color(51, 102, 255));
        btnActualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.white, null, null));
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarMouseExited(evt);
            }
        });
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(51, 102, 255));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.white, null, null));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panVisualizarUsuarioLayout = new javax.swing.GroupLayout(panVisualizarUsuario);
        panVisualizarUsuario.setLayout(panVisualizarUsuarioLayout);
        panVisualizarUsuarioLayout.setHorizontalGroup(
            panVisualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panVisualizarUsuarioLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(btnCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(panVisualizarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(panVisualizarUsuarioLayout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panVisualizarUsuarioLayout.setVerticalGroup(
            panVisualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panVisualizarUsuarioLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panVisualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panVisualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        panBitacora.addTab("Visualizar Usuario", panVisualizarUsuario);

        panCrearUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                panCrearUsuarioFocusGained(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        jLabel3.setText("Cédula:");

        jLabel4.setText("Teléfono:");

        jLabel5.setText("E-mail:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNombrePersona, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                        .addComponent(txtApellidoPersona))
                    .addComponent(txtCorreoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCedulaPersona, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(txtTelefonoPersona))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtNombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCedulaPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtApellidoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCorreoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Inicio Sesion"));

        jLabel6.setText("Nombre Usuario:");

        jLabel7.setText("Contraseña:");

        jLabel8.setText("Código de Seguridad:");

        txtCodigoSeguridadPersona.setEnabled(false);

        jButton5.setText("Añadir Usuario");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Regresar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtUsuarioPersona, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtContraseñaPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCodigoSeguridadPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUsuarioPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtContraseñaPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCodigoSeguridadPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panCrearUsuarioLayout = new javax.swing.GroupLayout(panCrearUsuario);
        panCrearUsuario.setLayout(panCrearUsuarioLayout);
        panCrearUsuarioLayout.setHorizontalGroup(
            panCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCrearUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panCrearUsuarioLayout.setVerticalGroup(
            panCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCrearUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        panBitacora.addTab("Crear Usuario", panCrearUsuario);

        panDatosUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel9.setText("Nombre:");

        jLabel14.setText("Apellido:");

        jLabel15.setText("Cédula:");

        jLabel16.setText("Teléfono:");

        jLabel17.setText("E-mail:");

        lblNumeroId.setText(".");

        jLabel22.setText("Numero Usuario:");

        javax.swing.GroupLayout panDatosUsuarioLayout = new javax.swing.GroupLayout(panDatosUsuario);
        panDatosUsuario.setLayout(panDatosUsuarioLayout);
        panDatosUsuarioLayout.setHorizontalGroup(
            panDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17))
                .addGap(39, 39, 39)
                .addGroup(panDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNombreActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                        .addComponent(txtApellidoActualizar))
                    .addComponent(txtCorreoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(panDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(58, 58, 58)
                .addGroup(panDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCedulaActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                        .addComponent(txtTelefonoActualizar))
                    .addComponent(lblNumeroId, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panDatosUsuarioLayout.setVerticalGroup(
            panDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel15)
                    .addComponent(txtNombreActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCedulaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(panDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(txtApellidoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(panDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtCorreoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panDatosInicio.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Inicio Sesion"));

        jLabel18.setText("Nombre Usuario:");

        jLabel19.setText("Contraseña:");

        jLabel20.setText("Código de Seguridad:");

        txtCodigoSeguridadActualizar.setEnabled(false);

        btnregresar.setText("Regresar");
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });

        btnActualizat.setText("Actualizar Datos");
        btnActualizat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panDatosInicioLayout = new javax.swing.GroupLayout(panDatosInicio);
        panDatosInicio.setLayout(panDatosInicioLayout);
        panDatosInicioLayout.setHorizontalGroup(
            panDatosInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panDatosInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDatosInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDatosInicioLayout.createSequentialGroup()
                        .addComponent(txtUsuarioActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                        .addGap(57, 57, 57))
                    .addGroup(panDatosInicioLayout.createSequentialGroup()
                        .addComponent(txtCodigoSeguridadActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panDatosInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDatosInicioLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(txtContraseñaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panDatosInicioLayout.createSequentialGroup()
                        .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizat)))
                .addGap(84, 84, 84))
        );
        panDatosInicioLayout.setVerticalGroup(
            panDatosInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosInicioLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panDatosInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtUsuarioActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtContraseñaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDatosInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDatosInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(txtCodigoSeguridadActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panDatosInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnActualizat)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panEditarUsuarioLayout = new javax.swing.GroupLayout(panEditarUsuario);
        panEditarUsuario.setLayout(panEditarUsuarioLayout);
        panEditarUsuarioLayout.setHorizontalGroup(
            panEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEditarUsuarioLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panDatosInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        panEditarUsuarioLayout.setVerticalGroup(
            panEditarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEditarUsuarioLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panDatosInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        panBitacora.addTab("Editar Usuario", panEditarUsuario);

        lblReferencia.setText("Ventana de opciones de Roles y Asignación:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Añadir Nuevo Rol"));

        jLabel10.setText("Digite el nombre del nuevo rol:");

        txtNuevoRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoRolActionPerformed(evt);
            }
        });

        btnAgregarRol.setText("Agregar");
        btnAgregarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtNuevoRol, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnAgregarRol)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(txtNuevoRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnAgregarRol)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccionar Rol a persona"));

        jScrollPane2.setViewportView(lstListaPersonas);

        btnAgregarRolPersona.setText("Agregar");
        btnAgregarRolPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRolPersonaActionPerformed(evt);
            }
        });

        jLabel12.setText("Persona:");

        jLabel13.setText("Rol:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(btnAgregarRolPersona)
                        .addGap(34, 34, 34))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(btnAgregarRolPersona))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout panAñadirRolLayout = new javax.swing.GroupLayout(panAñadirRol);
        panAñadirRol.setLayout(panAñadirRolLayout);
        panAñadirRolLayout.setHorizontalGroup(
            panAñadirRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAñadirRolLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panAñadirRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReferencia)
                    .addGroup(panAñadirRolLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panAñadirRolLayout.setVerticalGroup(
            panAñadirRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAñadirRolLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(panAñadirRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        panBitacora.addTab("Añadir Nuevo Rol", panAñadirRol);

        panAñadirPrvilegios.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                panAñadirPrvilegiosFocusGained(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Requerimientos"));

        cmbRequerimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRequerimientosActionPerformed(evt);
            }
        });

        jLabel11.setText("*Requerimientos del sistema");

        btnAgregarPrivilegios.setText("Agregar");
        btnAgregarPrivilegios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPrivilegiosActionPerformed(evt);
            }
        });

        lblMensajePrivilegios.setText("jLabel21");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(cmbRequerimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(201, 201, 201)
                                .addComponent(btnAgregarPrivilegios, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lblMensajePrivilegios)))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblMensajePrivilegios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRequerimientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarPrivilegios))
                .addGap(79, 79, 79))
        );

        javax.swing.GroupLayout panAñadirPrvilegiosLayout = new javax.swing.GroupLayout(panAñadirPrvilegios);
        panAñadirPrvilegios.setLayout(panAñadirPrvilegiosLayout);
        panAñadirPrvilegiosLayout.setHorizontalGroup(
            panAñadirPrvilegiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAñadirPrvilegiosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panAñadirPrvilegiosLayout.setVerticalGroup(
            panAñadirPrvilegiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAñadirPrvilegiosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        panBitacora.addTab("Privilegios", panAñadirPrvilegios);

        tblBitacora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Usuario", "Acción", "Fecha y hora ingreso", "Fecha y hora salida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblBitacora);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        panBitacora.addTab("Biitacora Usuarios", jPanel4);

        jTabbedPane1.addTab("Gestionar Usuarios", panBitacora);

        jMenu1.setText("Menú");
        jMenu1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jMenu1ItemStateChanged(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Ayuda");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jmSalir.setText("Salir del Sistema");
        jmSalir.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jmSalirItemStateChanged(evt);
            }
        });
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jmSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuarioActionPerformed
        
        
        int n = JOptionPane.showConfirmDialog(null, "¿Deseas Crear un nuevo usuario?","Informacion",JOptionPane.YES_OPTION);
        if(n == JOptionPane.YES_OPTION){
            panBitacora.setEnabledAt(1,true);
            panBitacora.setSelectedIndex(1);
              //cargar codigo seguridad
        cargarCodigo();
       
        }
        
    }//GEN-LAST:event_btnCrearUsuarioActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 
        String nombre = txtNombrePersona.getText();
        String apellido = txtApellidoPersona.getText();
        String cedula = txtCedulaPersona.getText();
        String telefono=txtTelefonoPersona.getText();
        String correo = txtCorreoPersona.getText();
        String usuario = txtUsuarioPersona.getText();
        String password = txtContraseñaPersona.getText();
        String codigoSeguridad =txtCodigoSeguridadPersona.getText();
         
        if(nombre.isEmpty() || apellido.isEmpty() || cedula.isEmpty() || telefono.isEmpty() || correo.isEmpty() || usuario.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor complete el campo", "Alerta",JOptionPane.ERROR_MESSAGE);
            return;
        }
          
            boolean algo = añadirUsuarioPersona(nombre, apellido, cedula, telefono, correo, usuario, password, codigoSeguridad);
            
            if(algo == false){
                JOptionPane.showMessageDialog(null, "Error 444");
                return;
            } 

                JOptionPane.showMessageDialog(null, "Usuario Regristrado con exito", "Información", JOptionPane.INFORMATION_MESSAGE);
                
                    txtNombrePersona.setText("");
                    txtApellidoPersona.setText("");
                    txtCedulaPersona.setText("");
                    txtTelefonoPersona.setText("");
                    txtCorreoPersona.setText("");
                    txtUsuarioPersona.setText("");
                    txtContraseñaPersona.setText("");
                    txtCodigoSeguridadPersona.setText("");

                    panBitacora.setSelectedIndex(0);
                    eliminar();
                    mostrarTablaUsuario();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        añadirRolComboBox();
        añadirRequerimiento();
        añadirListaPersona();
        
        
    }//GEN-LAST:event_formWindowActivated

    private void panVisualizarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panVisualizarUsuarioMouseClicked
       
    }//GEN-LAST:event_panVisualizarUsuarioMouseClicked

    private void panVisualizarUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panVisualizarUsuarioFocusLost
       
    }//GEN-LAST:event_panVisualizarUsuarioFocusLost

    private void panCrearUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panCrearUsuarioFocusGained
       panBitacora.setEnabledAt(1, false);
    }//GEN-LAST:event_panCrearUsuarioFocusGained

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        panBitacora.setSelectedIndex(0);
        panBitacora.setEnabledAt(1, false);
        panBitacora.setEnabledAt(0, true);
        panBitacora.setEnabledAt(2, true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtNuevoRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoRolActionPerformed
        
        
        
    }//GEN-LAST:event_txtNuevoRolActionPerformed
//NO SE OBSERVA UN DIAGRAMA DE SECUENCIA 
    private void btnAgregarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRolActionPerformed
       
        String rol = txtNuevoRol.getText();
        
        ArrayList<String> exis = validarRol(rol);
            if(exis.isEmpty()){
                
                boolean add = aggNuevoRol(rol);
                
                if(add == false){
                    JOptionPane.showMessageDialog(null, "Error 444");
                    return;
                }
                
                    JOptionPane.showMessageDialog(null, "Rol Agregado Exitosamente","Información",JOptionPane.INFORMATION_MESSAGE);
                    txtNuevoRol.setText("");
                    cargarRolA();
                    añadirRolComboBox();
                
                return;
            }
            
            JOptionPane.showMessageDialog(null, "Ya se encuentra este Rol registrado","Advertencia",JOptionPane.WARNING_MESSAGE);   
        
    }//GEN-LAST:event_btnAgregarRolActionPerformed

    private void panAñadirPrvilegiosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panAñadirPrvilegiosFocusGained
        añadirRequerimiento();
    }//GEN-LAST:event_panAñadirPrvilegiosFocusGained

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jMenu1ItemStateChanged
       
        
    }//GEN-LAST:event_jMenu1ItemStateChanged

    private void jmSalirItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jmSalirItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jmSalirItemStateChanged

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        // TODO add your handling code here:
        int dato =JOptionPane.showConfirmDialog(null, "¿Deseas Cerrar Sesion?", "Confirmacón", JOptionPane.YES_OPTION);
        if(dato == JOptionPane.YES_OPTION){
            this.dispose();
            this.sesion = new FormIniciarSesion();
            this.sesion.setVisible(true);
            return;
        }
    }//GEN-LAST:event_jmSalirActionPerformed

    private void cmbRequerimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRequerimientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRequerimientosActionPerformed

    //NO SE OBSERVA DIAGRAMA DE SECUENCIA
    private void btnAgregarRolPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRolPersonaActionPerformed
        String personaNom = lstListaPersonas.getSelectedValue();
        String rolNom = cmbRol.getSelectedItem().toString();
        
        ArrayList<String> consultaId = consultaIDPersonaRol(personaNom, rolNom);
        
        String separarId = consultaId.toString();
        
        String[] partesId = separarId.split("/");
        idPersona = partesId[0];
        parte2Id = partesId[1];
        
        idPersona = idPersona.replace("[", "");
        
        boolean resultado = insertarRolPersona(idPersona, parte2Id);
        if(resultado == false){
            JOptionPane.showMessageDialog(null, "Error 444");
            return;
        }  
            
            JOptionPane.showMessageDialog(null, "Se añadio el rol "+rolNom+" a la Persona "+personaNom+" exitosamente","Información",JOptionPane.INFORMATION_MESSAGE);
            panBitacora.setSelectedIndex(4);
            lblMensajePrivilegios.setText("Ahora, a la persona: "+personaNom+" con el rol "+rolNom+" Seleccione sus respectivos privilegios: ");
    }//GEN-LAST:event_btnAgregarRolPersonaActionPerformed

    private void asignarPrivilegiosRol(){
        
    }
    
    
    
    private void btnCrearUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearUsuarioMouseEntered
        btnCrearUsuario.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_btnCrearUsuarioMouseEntered

    private void btnCrearUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearUsuarioMouseExited
        btnCrearUsuario.setBackground(new Color(51,102,255));
    }//GEN-LAST:event_btnCrearUsuarioMouseExited

    private void btnActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseEntered
        btnActualizar.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_btnActualizarMouseEntered

    private void btnActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseExited
        btnActualizar.setBackground(new Color(51,102,255));
    }//GEN-LAST:event_btnActualizarMouseExited

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        btnEliminar.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        btnEliminar.setBackground(new Color(51,102,255));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnActualizatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizatActionPerformed
      
        String idPers = lblNumeroId.getText();
        String nombre = txtNombreActualizar.getText();
        String apellido = txtApellidoActualizar.getText();
        String cedula = txtCedulaActualizar.getText();
        String telefono=txtTelefonoActualizar.getText();
        String correo = txtCorreoActualizar.getText();
        String usuario = txtUsuarioActualizar.getText();
        String password = txtContraseñaActualizar.getText();
        String codigoSeguridad =txtCodigoSeguridadActualizar.getText();
         
        if(nombre.isEmpty() || apellido.isEmpty() || cedula.isEmpty() || telefono.isEmpty() || correo.isEmpty() || usuario.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor complete el campo", "Alerta",JOptionPane.ERROR_MESSAGE);
            return;
        }
          
            boolean algo = actualizarUsuarioPersona(nombre, apellido, cedula, telefono, correo, usuario, password, idPers);
            
            if(algo == false){
                JOptionPane.showMessageDialog(null, "Error 444");
                return;
            } 
                
                JOptionPane.showMessageDialog(null, "Usuario Actualizado con exito", "Información", JOptionPane.INFORMATION_MESSAGE);
                
                panBitacora.setSelectedIndex(0);
                  eliminar();
                  mostrarTablaUsuario();
        
    }//GEN-LAST:event_btnActualizatActionPerformed
    
    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnregresarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int fila = tblDatos.getSelectedRow();
        if(fila == -1){
            JOptionPane.showMessageDialog(null,"Debe seleccionar una fila para Actualizar");
            return;
        } 
        
            int n = JOptionPane.showConfirmDialog(null, "¿Deseas Actualizar este usuario?","Información",JOptionPane.YES_OPTION);
            if(n == JOptionPane.YES_OPTION){
                nomUsuario= tblDatos.getValueAt(fila, 3).toString();
                
                panBitacora.setSelectedIndex(2);
                
                
                
                //llamar metodo
                obtenerDatosPersona(nomUsuario);
                
                /*
                //lenar los jtextfield
                lblNumeroId.setText(person.getIdPersona().replace("[", ""));
                txtNombreActualizar.setText(person.getNombre());
                txtApellidoActualizar.setText(person.getApellido());
                txtCedulaActualizar.setText(person.getCedula());
                txtTelefonoActualizar.setText(person.getTelefono());
                txtCorreoActualizar.setText(person.getEmail());
                txtUsuarioActualizar.setText(person.getUsuario());
                txtContraseñaActualizar.setText(person.getPassword());
                txtCodigoSeguridadActualizar.setText(person.getCodigoSeguridad()); */
                
                return;
            }
            
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        int fila2 = tblDatos.getSelectedRow();
       
        int info = JOptionPane.showConfirmDialog(null, "¿Seguro quieres eliminar?");
        
        if(JOptionPane.YES_OPTION==info){
        
            if (fila2 >= 0) { 
                int fila = tblDatos.getSelectedRow();
                String valor= tblDatos.getValueAt(fila, 0).toString();
                
                if(fila>0){
                    
                    eliminarUsuario(valor);
                    JOptionPane.showMessageDialog(null, "Usuario Eliminado Exitosamente");
                    eliminar();
                    mostrarTablaUsuario();
                    return;
                } 
                
                return;
            } 
            
            JOptionPane.showMessageDialog(null, "Seleccione una fila primero");
        
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarPrivilegiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPrivilegiosActionPerformed
        
        ArrayList<String> obtener = obtenerRolPersona(parte2Id, idPersona);
        String obt = obtener.toString().replace("/","").replace("[", "").replace("]", "");
        
        String requeri = cmbRequerimientos.getSelectedItem().toString();
        
        ArrayList<String> obR = obtenerIdRequerimiento(requeri);
        String obtencionReq = obR.toString().replace("/","").replace("[", "").replace("]", "");
        boolean alg = insertarPrivilegios(obt, obtencionReq);
        if(alg == false){
            JOptionPane.showMessageDialog(null, "Error 444");
            return;
        }
        
            JOptionPane.showMessageDialog(null, "Privilegio Asignado a la Persona Correctamente");
        
    }//GEN-LAST:event_btnAgregarPrivilegiosActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizat;
    private javax.swing.JButton btnAgregarPrivilegios;
    private javax.swing.JButton btnAgregarRol;
    private javax.swing.JButton btnAgregarRolPersona;
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnregresar;
    private javax.swing.JComboBox<String> cmbRequerimientos;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuItem jmSalir;
    private javax.swing.JLabel lblMensajePrivilegios;
    private javax.swing.JLabel lblNumeroId;
    private javax.swing.JLabel lblReferencia;
    private javax.swing.JList<String> lstListaPersonas;
    private javax.swing.JPanel panAñadirPrvilegios;
    private javax.swing.JPanel panAñadirRol;
    private javax.swing.JTabbedPane panBitacora;
    private javax.swing.JPanel panCrearUsuario;
    private javax.swing.JPanel panDatosInicio;
    private javax.swing.JPanel panDatosUsuario;
    private javax.swing.JPanel panEditarUsuario;
    private javax.swing.JPanel panVisualizarUsuario;
    private javax.swing.JTable tblBitacora;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtApellidoActualizar;
    private javax.swing.JTextField txtApellidoPersona;
    private javax.swing.JTextField txtCedulaActualizar;
    private javax.swing.JTextField txtCedulaPersona;
    private javax.swing.JTextField txtCodigoSeguridadActualizar;
    private javax.swing.JTextField txtCodigoSeguridadPersona;
    private javax.swing.JTextField txtContraseñaActualizar;
    private javax.swing.JTextField txtContraseñaPersona;
    private javax.swing.JTextField txtCorreoActualizar;
    private javax.swing.JTextField txtCorreoPersona;
    private javax.swing.JTextField txtNombreActualizar;
    private javax.swing.JTextField txtNombrePersona;
    private javax.swing.JTextField txtNuevoRol;
    private javax.swing.JTextField txtTelefonoActualizar;
    private javax.swing.JTextField txtTelefonoPersona;
    private javax.swing.JTextField txtUsuarioActualizar;
    private javax.swing.JTextField txtUsuarioPersona;
    // End of variables declaration//GEN-END:variables

    private void cargarPrivilegios(ArrayList<String> privilegios){
        
        for (String privilegio : privilegios) {
            
            switch (privilegio.split("/")[0]){
                case "admi":
                    
                    break;
                    
                
            }
            
        }
        
    }
    
    public void eliminar(){
        DefaultTableModel tb = (DefaultTableModel) tblDatos.getModel();
        int a = tblDatos.getRowCount()-1;
        for (int i = a; i >= 0; i--) {           
        tb.removeRow(tb.getRowCount()-1);
        } 
    }
    
    private ArrayList<String> obtenerTodos(){
        ArrayList<String> dato;
        dato=faca.obtenerTodos();
        return dato;
    }
    
    private void mostrarTablaUsuario(){
        
                
        ArrayList<String> datoPersona;
        datoPersona=obtenerTodos();
    
        DefaultTableModel modelo = (DefaultTableModel) tblDatos.getModel();
        Object[] fila=new Object[modelo.getColumnCount()]; 
        
        for (int i = 0; i < datoPersona.size(); i++) {
            String dato1=datoPersona.get(i).toString();
            String[] dato2 = dato1.split("/");
            fila[0] = dato2[0];
            fila[1] = dato2[1];
            fila[2] = dato2[5];
            fila[3] = dato2[6];
            modelo.addRow(fila);
        }
        
        tblDatos.setModel(modelo);
        
    }
    
     private void mostrarTablaBitacora(){
        
              
        ArrayList<String> datoPersona;
        datoPersona=obtenerTodos();
        
         
        DefaultTableModel modelo = (DefaultTableModel) tblBitacora.getModel();
        Object[] fila=new Object[modelo.getColumnCount()]; 
        
        for (int i = 0; i < datoPersona.size(); i++) {
            String dato1=datoPersona.get(i).toString();
            String[] dato2 = dato1.split("/");
            fila[0] = dato2[1];
          
            modelo.addRow(fila);
        }
        
        tblBitacora.setModel(modelo);
        
    }
    
    private boolean añadirUsuarioPersona(String nombre, String apellido, String cedula, String telefono, String correo, String usuario, String password, String codigoSeguridad){
        return faca.añadirUsuarioPersona(nombre, apellido,cedula,telefono,correo,usuario,password,codigoSeguridad);
    }
    
    private ArrayList<String> cargarRolA(){
        ArrayList<String> rol;
        rol = faca.cargarRoles();
        return rol;
    }

    private boolean aggNuevoRol(String rol) {
        return faca.aggNuevoRol(rol);
    }
    
    private void añadirRolComboBox(){
        cmbRol.removeAllItems();
        
        ArrayList<String> roles = cargarRolA();
        
        cmbRol.addItem("Seleccione");
        
        for(String campos : roles) {
        cmbRol.addItem(campos.replace("/", ""));
        } 
        
    }
  
    private ArrayList<String> validarRol(String rol) {
        ArrayList<String> vali;
        vali = faca.validarRol(rol);
        return vali;
    }
    
    private ArrayList<String> cargarRequimientos(){
        ArrayList<String>reque;
        reque=faca.cargarRequimientos();
        return reque;
    }
    
    private ArrayList<String> obtenerIdRequerimiento(String nom){
        ArrayList<String>req;
        req=faca.obtenerIdRequerimiento(nom);
        return req;
    }
    
    private void añadirRequerimiento(){
        cmbRequerimientos.removeAllItems();
        
        ArrayList<String> requerimiento = cargarRequimientos();
        
        for(String campos : requerimiento) {
            cmbRequerimientos.addItem(campos.replace("/", ""));
        }
    }
    
    private void añadirListaPersona(){
        lstListaPersonas.removeAll();
        
        ArrayList<String> datoPersona;
        datoPersona=obtenerTodos();
    
        DefaultListModel modelo = new DefaultListModel(); 
        
        for (int i = 0; i < datoPersona.size(); i++) {
            String dato1=datoPersona.get(i).toString();
            String[] dato2 = dato1.split("/");
            String jaa = dato2[1];
            modelo.addElement(jaa);
        }
        
        lstListaPersonas.setModel(modelo);
    }
    
    private ArrayList<String> consultaIDPersonaRol(String persona, String rol){
        ArrayList<String> consul;
        consul = faca.consultaIDPersonaRol(persona, rol);
        return consul;
    }

    private boolean insertarRolPersona(String idPerso, String idRol) {
        return faca.insertarRolPersona(idPerso, idRol);
    }
    
    private void cargarCodigo(){
       int []numeros;//aqui se declara el areglo
                numeros=new int [6];	//el areglo tiene seis elementos
                for (int i = 0; i<6; i++){	
                numeros[i]=(int)Math.floor((Math.random()*(100000)));	//crea numeros aleatorios 
                }
                //los jtexfield recogen los numeros aleatorios almacenados en un areglo
        txtCodigoSeguridadPersona.setText(Integer.toString(numeros[0]));
        System.out.println(Integer.toString(numeros[0]));
   }

    private boolean actualizarUsuarioPersona(String nombre, String apellido, String cedula, String telefono, String correo, String usuario, String password, String id) {
        return faca.actualizarUsuarioPersona(nombre, apellido,cedula,telefono,correo,usuario,password,id);
    }
    
    private ArrayList<String> obtenerDatosPersona(String id){
        ArrayList<String> obten;
        obten = faca.obtenerDatosPersona(id);
        return obten;
    }

    private boolean eliminarUsuario(String valor) {
        return faca.eliminarUsuario(valor);
    }
    
    private ArrayList<String> obtenerRolPersona(String rol, String per){
        ArrayList<String> obt;
        obt = faca.obtenerRolPersona(rol, per);
        return obt;
    }

    private boolean insertarPrivilegios(String idRoPer, String idReq) {
        return faca.insertarPrivilegios(idRoPer, idReq);
    }
    
}
